default_stages: [pre-commit, pre-push]
fail_fast: false
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
    -   id: trailing-whitespace
-   repo: local
    hooks:
    -   id: debug-comments
        name: debug-comments
        entry: '#\s*DEBUG'
        language: pygrep
        types: [python]
    -   id: black
        name: black
        entry: uv run --all-groups black --check --diff
        language: system
        types: [python]
    -   id: isort
        name: isort
        entry: uv run --all-groups isort --check-only --diff
        language: system
        types: [python]
