name: Tests

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:

  run_tests:
    name: ${{ matrix.title }} (Python ${{ matrix.python }} on ${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - title: Lint and Main Tests
            os: ubuntu-latest
            python: "3.12"
            commands: |
              make lint
              make PYTHON=3.12 test
            coverage: true
          - title: Oldest supported Python
            os: ubuntu-latest
            python: "3.10"
            commands: make PYTHON=3.10 test-lowest
            coverage: true
          - title: Windows
            os: windows-latest
            python: "3.11"
            commands: make PYTHON=3.11 test
            coverage: false
          - title: MacOS / Latest Python
            os: macos-latest
            python: "3.13"
            commands: make PYTHON=3.13 test
            coverage: true
    steps:

      - uses: actions/checkout@v7

      - name: Install uv
        uses: astral-sh/setup-uv@v8.2.0
        with:
          python-version: ${{ matrix.python }}

      - name: Run Commands
        run: ${{ matrix.commands }}

      - uses: codecov/codecov-action@v7
        if: matrix.coverage == true
        with:
          verbose: false
